// <auto-generated />
using Fives;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fives.Migrations
{
    [DbContext(typeof(DominionDbContext))]
    partial class DominionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Fives.AgendaDb", b =>
                {
                    b.Property<string>("Cards")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Duchies");

                    b.Property<int>("Estates");

                    b.Property<int>("Provinces");

                    b.HasKey("Cards");

                    b.ToTable("Fives");
                });

            modelBuilder.Entity("Fives.BuyMenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AgendaDbCards");

                    b.Property<int>("CardId");

                    b.Property<int>("Number");

                    b.HasKey("Id");

                    b.HasIndex("AgendaDbCards");

                    b.ToTable("BuyMenuItem");
                });

            modelBuilder.Entity("Fives.BuyMenuItem", b =>
                {
                    b.HasOne("Fives.AgendaDb")
                        .WithMany("BuyMenu")
                        .HasForeignKey("AgendaDbCards");
                });
#pragma warning restore 612, 618
        }
    }
}
